// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies;

public class Article implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject articleMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MasterData.Article";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Code("Code"),
		StockLevel("StockLevel"),
		Article_Location("MasterData.Article_Location"),
		Order_Article("MasterData.Order_Article"),
		Article_RetailPrice("MasterData.Article_RetailPrice");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Article(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Article(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject articleMendixObject)
	{
		if (articleMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, articleMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.articleMendixObject = articleMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static masterdata.proxies.Article initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new masterdata.proxies.Article(context, mendixObject);
	}

	public static masterdata.proxies.Article load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return masterdata.proxies.Article.initialize(context, mendixObject);
	}

	public static java.util.List<masterdata.proxies.Article> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> masterdata.proxies.Article.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Code
	 */
	public final java.lang.String getCode()
	{
		return getCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Code
	 */
	public final java.lang.String getCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Code.toString());
	}

	/**
	 * Set value of Code
	 * @param code
	 */
	public final void setCode(java.lang.String code)
	{
		setCode(getContext(), code);
	}

	/**
	 * Set value of Code
	 * @param context
	 * @param code
	 */
	public final void setCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String code)
	{
		getMendixObject().setValue(context, MemberNames.Code.toString(), code);
	}

	/**
	 * @return value of StockLevel
	 */
	public final java.lang.String getStockLevel()
	{
		return getStockLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of StockLevel
	 */
	public final java.lang.String getStockLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StockLevel.toString());
	}

	/**
	 * Set value of StockLevel
	 * @param stocklevel
	 */
	public final void setStockLevel(java.lang.String stocklevel)
	{
		setStockLevel(getContext(), stocklevel);
	}

	/**
	 * Set value of StockLevel
	 * @param context
	 * @param stocklevel
	 */
	public final void setStockLevel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stocklevel)
	{
		getMendixObject().setValue(context, MemberNames.StockLevel.toString(), stocklevel);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Article_Location
	 */
	public final java.util.List<masterdata.proxies.Location> getArticle_Location() throws com.mendix.core.CoreException
	{
		return getArticle_Location(getContext());
	}

	/**
	 * @param context
	 * @return value of Article_Location
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<masterdata.proxies.Location> getArticle_Location(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<masterdata.proxies.Location> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Article_Location.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(masterdata.proxies.Location.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Article_Location
	 * @param article_location
	 */
	public final void setArticle_Location(java.util.List<masterdata.proxies.Location> article_location)
	{
		setArticle_Location(getContext(), article_location);
	}

	/**
	 * Set value of Article_Location
	 * @param context
	 * @param article_location
	 */
	public final void setArticle_Location(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<masterdata.proxies.Location> article_location)
	{
		var identifiers = article_location
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Article_Location.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Order_Article
	 */
	public final java.util.List<masterdata.proxies.Order> getOrder_Article() throws com.mendix.core.CoreException
	{
		return getOrder_Article(getContext());
	}

	/**
	 * @param context
	 * @return value of Order_Article
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<masterdata.proxies.Order> getOrder_Article(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<masterdata.proxies.Order> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Order_Article.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(masterdata.proxies.Order.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Order_Article
	 * @param order_article
	 */
	public final void setOrder_Article(java.util.List<masterdata.proxies.Order> order_article)
	{
		setOrder_Article(getContext(), order_article);
	}

	/**
	 * Set value of Order_Article
	 * @param context
	 * @param order_article
	 */
	public final void setOrder_Article(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<masterdata.proxies.Order> order_article)
	{
		var identifiers = order_article
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Order_Article.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Article_RetailPrice
	 */
	public final masterdata.proxies.RetailPrice getArticle_RetailPrice() throws com.mendix.core.CoreException
	{
		return getArticle_RetailPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of Article_RetailPrice
	 * @throws com.mendix.core.CoreException
	 */
	public final masterdata.proxies.RetailPrice getArticle_RetailPrice(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.RetailPrice result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Article_RetailPrice.toString());
		if (identifier != null) {
			result = masterdata.proxies.RetailPrice.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Article_RetailPrice
	 * @param article_retailprice
	 */
	public final void setArticle_RetailPrice(masterdata.proxies.RetailPrice article_retailprice)
	{
		setArticle_RetailPrice(getContext(), article_retailprice);
	}

	/**
	 * Set value of Article_RetailPrice
	 * @param context
	 * @param article_retailprice
	 */
	public final void setArticle_RetailPrice(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.RetailPrice article_retailprice)
	{
		if (article_retailprice == null) {
			getMendixObject().setValue(context, MemberNames.Article_RetailPrice.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Article_RetailPrice.toString(), article_retailprice.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return articleMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final masterdata.proxies.Article that = (masterdata.proxies.Article) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
