// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies;

public class Location implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject locationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MasterData.Location";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		LocationID("LocationID"),
		Aisle("Aisle"),
		Shelf("Shelf"),
		Rack("Rack"),
		Capacity("Capacity"),
		OccupancyPercentage("OccupancyPercentage"),
		Location_Warehouse("MasterData.Location_Warehouse"),
		Article_Location("MasterData.Article_Location");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Location(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Location(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject locationMendixObject)
	{
		if (locationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, locationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.locationMendixObject = locationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static masterdata.proxies.Location initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new masterdata.proxies.Location(context, mendixObject);
	}

	public static masterdata.proxies.Location load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return masterdata.proxies.Location.initialize(context, mendixObject);
	}

	public static java.util.List<masterdata.proxies.Location> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> masterdata.proxies.Location.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of LocationID
	 */
	public final java.lang.Long getLocationID()
	{
		return getLocationID(getContext());
	}

	/**
	 * @param context
	 * @return value of LocationID
	 */
	public final java.lang.Long getLocationID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.LocationID.toString());
	}

	/**
	 * Set value of LocationID
	 * @param locationid
	 */
	public final void setLocationID(java.lang.Long locationid)
	{
		setLocationID(getContext(), locationid);
	}

	/**
	 * Set value of LocationID
	 * @param context
	 * @param locationid
	 */
	public final void setLocationID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long locationid)
	{
		getMendixObject().setValue(context, MemberNames.LocationID.toString(), locationid);
	}

	/**
	 * @return value of Aisle
	 */
	public final java.lang.String getAisle()
	{
		return getAisle(getContext());
	}

	/**
	 * @param context
	 * @return value of Aisle
	 */
	public final java.lang.String getAisle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Aisle.toString());
	}

	/**
	 * Set value of Aisle
	 * @param aisle
	 */
	public final void setAisle(java.lang.String aisle)
	{
		setAisle(getContext(), aisle);
	}

	/**
	 * Set value of Aisle
	 * @param context
	 * @param aisle
	 */
	public final void setAisle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String aisle)
	{
		getMendixObject().setValue(context, MemberNames.Aisle.toString(), aisle);
	}

	/**
	 * @return value of Shelf
	 */
	public final java.lang.Integer getShelf()
	{
		return getShelf(getContext());
	}

	/**
	 * @param context
	 * @return value of Shelf
	 */
	public final java.lang.Integer getShelf(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Shelf.toString());
	}

	/**
	 * Set value of Shelf
	 * @param shelf
	 */
	public final void setShelf(java.lang.Integer shelf)
	{
		setShelf(getContext(), shelf);
	}

	/**
	 * Set value of Shelf
	 * @param context
	 * @param shelf
	 */
	public final void setShelf(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer shelf)
	{
		getMendixObject().setValue(context, MemberNames.Shelf.toString(), shelf);
	}

	/**
	 * @return value of Rack
	 */
	public final java.lang.Integer getRack()
	{
		return getRack(getContext());
	}

	/**
	 * @param context
	 * @return value of Rack
	 */
	public final java.lang.Integer getRack(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Rack.toString());
	}

	/**
	 * Set value of Rack
	 * @param rack
	 */
	public final void setRack(java.lang.Integer rack)
	{
		setRack(getContext(), rack);
	}

	/**
	 * Set value of Rack
	 * @param context
	 * @param rack
	 */
	public final void setRack(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer rack)
	{
		getMendixObject().setValue(context, MemberNames.Rack.toString(), rack);
	}

	/**
	 * @return value of Capacity
	 */
	public final java.lang.Integer getCapacity()
	{
		return getCapacity(getContext());
	}

	/**
	 * @param context
	 * @return value of Capacity
	 */
	public final java.lang.Integer getCapacity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Capacity.toString());
	}

	/**
	 * Set value of Capacity
	 * @param capacity
	 */
	public final void setCapacity(java.lang.Integer capacity)
	{
		setCapacity(getContext(), capacity);
	}

	/**
	 * Set value of Capacity
	 * @param context
	 * @param capacity
	 */
	public final void setCapacity(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer capacity)
	{
		getMendixObject().setValue(context, MemberNames.Capacity.toString(), capacity);
	}

	/**
	 * @return value of OccupancyPercentage
	 */
	public final java.math.BigDecimal getOccupancyPercentage()
	{
		return getOccupancyPercentage(getContext());
	}

	/**
	 * @param context
	 * @return value of OccupancyPercentage
	 */
	public final java.math.BigDecimal getOccupancyPercentage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.OccupancyPercentage.toString());
	}

	/**
	 * Set value of OccupancyPercentage
	 * @param occupancypercentage
	 */
	public final void setOccupancyPercentage(java.math.BigDecimal occupancypercentage)
	{
		setOccupancyPercentage(getContext(), occupancypercentage);
	}

	/**
	 * Set value of OccupancyPercentage
	 * @param context
	 * @param occupancypercentage
	 */
	public final void setOccupancyPercentage(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal occupancypercentage)
	{
		getMendixObject().setValue(context, MemberNames.OccupancyPercentage.toString(), occupancypercentage);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Location_Warehouse
	 */
	public final masterdata.proxies.Warehouse getLocation_Warehouse() throws com.mendix.core.CoreException
	{
		return getLocation_Warehouse(getContext());
	}

	/**
	 * @param context
	 * @return value of Location_Warehouse
	 * @throws com.mendix.core.CoreException
	 */
	public final masterdata.proxies.Warehouse getLocation_Warehouse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.Warehouse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Location_Warehouse.toString());
		if (identifier != null) {
			result = masterdata.proxies.Warehouse.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Location_Warehouse
	 * @param location_warehouse
	 */
	public final void setLocation_Warehouse(masterdata.proxies.Warehouse location_warehouse)
	{
		setLocation_Warehouse(getContext(), location_warehouse);
	}

	/**
	 * Set value of Location_Warehouse
	 * @param context
	 * @param location_warehouse
	 */
	public final void setLocation_Warehouse(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.Warehouse location_warehouse)
	{
		if (location_warehouse == null) {
			getMendixObject().setValue(context, MemberNames.Location_Warehouse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Location_Warehouse.toString(), location_warehouse.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Article_Location
	 */
	public final java.util.List<masterdata.proxies.Article> getArticle_Location() throws com.mendix.core.CoreException
	{
		return getArticle_Location(getContext());
	}

	/**
	 * @param context
	 * @return value of Article_Location
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<masterdata.proxies.Article> getArticle_Location(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<masterdata.proxies.Article> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Article_Location.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(masterdata.proxies.Article.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Article_Location
	 * @param article_location
	 */
	public final void setArticle_Location(java.util.List<masterdata.proxies.Article> article_location)
	{
		setArticle_Location(getContext(), article_location);
	}

	/**
	 * Set value of Article_Location
	 * @param context
	 * @param article_location
	 */
	public final void setArticle_Location(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<masterdata.proxies.Article> article_location)
	{
		var identifiers = article_location
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Article_Location.toString(), identifiers);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return locationMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final masterdata.proxies.Location that = (masterdata.proxies.Location) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
