// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies;

public class Manager extends masterdata.proxies.Person
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MasterData.Manager";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IsAssigned("IsAssigned"),
		FullName("FullName"),
		Email("Email"),
		NewPassword("NewPassword"),
		ConfirmPassword("ConfirmPassword"),
		Warehouse_Manager("MasterData.Warehouse_Manager"),
		Manager_TechAdmin("MasterData.Manager_TechAdmin"),
		Person_Account("MasterData.Person_Account");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Manager(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Manager(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject managerMendixObject)
	{
		super(context, managerMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, managerMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static masterdata.proxies.Manager initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new masterdata.proxies.Manager(context, mendixObject);
	}

	public static masterdata.proxies.Manager load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return masterdata.proxies.Manager.initialize(context, mendixObject);
	}

	public static java.util.List<masterdata.proxies.Manager> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> masterdata.proxies.Manager.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of IsAssigned
	 */
	public final java.lang.Boolean getIsAssigned()
	{
		return getIsAssigned(getContext());
	}

	/**
	 * @param context
	 * @return value of IsAssigned
	 */
	public final java.lang.Boolean getIsAssigned(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsAssigned.toString());
	}

	/**
	 * Set value of IsAssigned
	 * @param isassigned
	 */
	public final void setIsAssigned(java.lang.Boolean isassigned)
	{
		setIsAssigned(getContext(), isassigned);
	}

	/**
	 * Set value of IsAssigned
	 * @param context
	 * @param isassigned
	 */
	public final void setIsAssigned(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isassigned)
	{
		getMendixObject().setValue(context, MemberNames.IsAssigned.toString(), isassigned);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Warehouse_Manager
	 */
	public final masterdata.proxies.Warehouse getWarehouse_Manager() throws com.mendix.core.CoreException
	{
		return getWarehouse_Manager(getContext());
	}

	/**
	 * @param context
	 * @return value of Warehouse_Manager
	 * @throws com.mendix.core.CoreException
	 */
	public final masterdata.proxies.Warehouse getWarehouse_Manager(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.Warehouse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Warehouse_Manager.toString());
		if (identifier != null) {
			result = masterdata.proxies.Warehouse.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Warehouse_Manager
	 * @param warehouse_manager
	 */
	public final void setWarehouse_Manager(masterdata.proxies.Warehouse warehouse_manager)
	{
		setWarehouse_Manager(getContext(), warehouse_manager);
	}

	/**
	 * Set value of Warehouse_Manager
	 * @param context
	 * @param warehouse_manager
	 */
	public final void setWarehouse_Manager(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.Warehouse warehouse_manager)
	{
		if (warehouse_manager == null) {
			getMendixObject().setValue(context, MemberNames.Warehouse_Manager.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Warehouse_Manager.toString(), warehouse_manager.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Manager_TechAdmin
	 */
	public final masterdata.proxies.TechAdmin getManager_TechAdmin() throws com.mendix.core.CoreException
	{
		return getManager_TechAdmin(getContext());
	}

	/**
	 * @param context
	 * @return value of Manager_TechAdmin
	 * @throws com.mendix.core.CoreException
	 */
	public final masterdata.proxies.TechAdmin getManager_TechAdmin(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.TechAdmin result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Manager_TechAdmin.toString());
		if (identifier != null) {
			result = masterdata.proxies.TechAdmin.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Manager_TechAdmin
	 * @param manager_techadmin
	 */
	public final void setManager_TechAdmin(masterdata.proxies.TechAdmin manager_techadmin)
	{
		setManager_TechAdmin(getContext(), manager_techadmin);
	}

	/**
	 * Set value of Manager_TechAdmin
	 * @param context
	 * @param manager_techadmin
	 */
	public final void setManager_TechAdmin(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.TechAdmin manager_techadmin)
	{
		if (manager_techadmin == null) {
			getMendixObject().setValue(context, MemberNames.Manager_TechAdmin.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Manager_TechAdmin.toString(), manager_techadmin.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final masterdata.proxies.Manager that = (masterdata.proxies.Manager) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
