// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies;

public class OrderPicker extends masterdata.proxies.Person
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MasterData.OrderPicker";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		FullName("FullName"),
		Email("Email"),
		NewPassword("NewPassword"),
		ConfirmPassword("ConfirmPassword"),
		OrderPicker_Warehouse("MasterData.OrderPicker_Warehouse"),
		Person_Account("MasterData.Person_Account");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OrderPicker(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected OrderPicker(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject orderPickerMendixObject)
	{
		super(context, orderPickerMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, orderPickerMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static masterdata.proxies.OrderPicker initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new masterdata.proxies.OrderPicker(context, mendixObject);
	}

	public static masterdata.proxies.OrderPicker load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return masterdata.proxies.OrderPicker.initialize(context, mendixObject);
	}

	public static java.util.List<masterdata.proxies.OrderPicker> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> masterdata.proxies.OrderPicker.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of OrderPicker_Warehouse
	 */
	public final masterdata.proxies.Warehouse getOrderPicker_Warehouse() throws com.mendix.core.CoreException
	{
		return getOrderPicker_Warehouse(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderPicker_Warehouse
	 * @throws com.mendix.core.CoreException
	 */
	public final masterdata.proxies.Warehouse getOrderPicker_Warehouse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.Warehouse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OrderPicker_Warehouse.toString());
		if (identifier != null) {
			result = masterdata.proxies.Warehouse.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of OrderPicker_Warehouse
	 * @param orderpicker_warehouse
	 */
	public final void setOrderPicker_Warehouse(masterdata.proxies.Warehouse orderpicker_warehouse)
	{
		setOrderPicker_Warehouse(getContext(), orderpicker_warehouse);
	}

	/**
	 * Set value of OrderPicker_Warehouse
	 * @param context
	 * @param orderpicker_warehouse
	 */
	public final void setOrderPicker_Warehouse(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.Warehouse orderpicker_warehouse)
	{
		if (orderpicker_warehouse == null) {
			getMendixObject().setValue(context, MemberNames.OrderPicker_Warehouse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.OrderPicker_Warehouse.toString(), orderpicker_warehouse.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final masterdata.proxies.OrderPicker that = (masterdata.proxies.OrderPicker) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
