// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies;

public class RetailPrice implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject retailPriceMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MasterData.RetailPrice";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Price("Price"),
		ChangeDate("ChangeDate"),
		Source("Source"),
		RetailPrice_Article_History("MasterData.RetailPrice_Article_History"),
		Article_RetailPrice("MasterData.Article_RetailPrice");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RetailPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RetailPrice(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject retailPriceMendixObject)
	{
		if (retailPriceMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, retailPriceMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.retailPriceMendixObject = retailPriceMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static masterdata.proxies.RetailPrice initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new masterdata.proxies.RetailPrice(context, mendixObject);
	}

	public static masterdata.proxies.RetailPrice load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return masterdata.proxies.RetailPrice.initialize(context, mendixObject);
	}

	public static java.util.List<masterdata.proxies.RetailPrice> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> masterdata.proxies.RetailPrice.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Price
	 */
	public final java.math.BigDecimal getPrice()
	{
		return getPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of Price
	 */
	public final java.math.BigDecimal getPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Price.toString());
	}

	/**
	 * Set value of Price
	 * @param price
	 */
	public final void setPrice(java.math.BigDecimal price)
	{
		setPrice(getContext(), price);
	}

	/**
	 * Set value of Price
	 * @param context
	 * @param price
	 */
	public final void setPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal price)
	{
		getMendixObject().setValue(context, MemberNames.Price.toString(), price);
	}

	/**
	 * @return value of ChangeDate
	 */
	public final java.util.Date getChangeDate()
	{
		return getChangeDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ChangeDate
	 */
	public final java.util.Date getChangeDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ChangeDate.toString());
	}

	/**
	 * Set value of ChangeDate
	 * @param changedate
	 */
	public final void setChangeDate(java.util.Date changedate)
	{
		setChangeDate(getContext(), changedate);
	}

	/**
	 * Set value of ChangeDate
	 * @param context
	 * @param changedate
	 */
	public final void setChangeDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date changedate)
	{
		getMendixObject().setValue(context, MemberNames.ChangeDate.toString(), changedate);
	}

	/**
	 * @return value of Source
	 */
	public final java.lang.String getSource()
	{
		return getSource(getContext());
	}

	/**
	 * @param context
	 * @return value of Source
	 */
	public final java.lang.String getSource(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Source.toString());
	}

	/**
	 * Set value of Source
	 * @param source
	 */
	public final void setSource(java.lang.String source)
	{
		setSource(getContext(), source);
	}

	/**
	 * Set value of Source
	 * @param context
	 * @param source
	 */
	public final void setSource(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String source)
	{
		getMendixObject().setValue(context, MemberNames.Source.toString(), source);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RetailPrice_Article_History
	 */
	public final masterdata.proxies.Article getRetailPrice_Article_History() throws com.mendix.core.CoreException
	{
		return getRetailPrice_Article_History(getContext());
	}

	/**
	 * @param context
	 * @return value of RetailPrice_Article_History
	 * @throws com.mendix.core.CoreException
	 */
	public final masterdata.proxies.Article getRetailPrice_Article_History(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.Article result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.RetailPrice_Article_History.toString());
		if (identifier != null) {
			result = masterdata.proxies.Article.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of RetailPrice_Article_History
	 * @param retailprice_article_history
	 */
	public final void setRetailPrice_Article_History(masterdata.proxies.Article retailprice_article_history)
	{
		setRetailPrice_Article_History(getContext(), retailprice_article_history);
	}

	/**
	 * Set value of RetailPrice_Article_History
	 * @param context
	 * @param retailprice_article_history
	 */
	public final void setRetailPrice_Article_History(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.Article retailprice_article_history)
	{
		if (retailprice_article_history == null) {
			getMendixObject().setValue(context, MemberNames.RetailPrice_Article_History.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.RetailPrice_Article_History.toString(), retailprice_article_history.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Article_RetailPrice
	 */
	public final masterdata.proxies.Article getArticle_RetailPrice() throws com.mendix.core.CoreException
	{
		return getArticle_RetailPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of Article_RetailPrice
	 * @throws com.mendix.core.CoreException
	 */
	public final masterdata.proxies.Article getArticle_RetailPrice(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.Article result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Article_RetailPrice.toString());
		if (identifier != null) {
			result = masterdata.proxies.Article.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Article_RetailPrice
	 * @param article_retailprice
	 */
	public final void setArticle_RetailPrice(masterdata.proxies.Article article_retailprice)
	{
		setArticle_RetailPrice(getContext(), article_retailprice);
	}

	/**
	 * Set value of Article_RetailPrice
	 * @param context
	 * @param article_retailprice
	 */
	public final void setArticle_RetailPrice(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.Article article_retailprice)
	{
		if (article_retailprice == null) {
			getMendixObject().setValue(context, MemberNames.Article_RetailPrice.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Article_RetailPrice.toString(), article_retailprice.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return retailPriceMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final masterdata.proxies.RetailPrice that = (masterdata.proxies.RetailPrice) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
