// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package masterdata.proxies;

public class Shipment implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject shipmentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MasterData.Shipment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OrderNumber("OrderNumber"),
		WarehouseID("WarehouseID"),
		SendDate("SendDate"),
		ShipmentNumber("ShipmentNumber"),
		ModeOfTransportation("ModeOfTransportation"),
		Shipment_Order("MasterData.Shipment_Order");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Shipment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Shipment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject shipmentMendixObject)
	{
		if (shipmentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, shipmentMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.shipmentMendixObject = shipmentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static masterdata.proxies.Shipment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new masterdata.proxies.Shipment(context, mendixObject);
	}

	public static masterdata.proxies.Shipment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return masterdata.proxies.Shipment.initialize(context, mendixObject);
	}

	public static java.util.List<masterdata.proxies.Shipment> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> masterdata.proxies.Shipment.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of OrderNumber
	 */
	public final java.lang.Integer getOrderNumber()
	{
		return getOrderNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderNumber
	 */
	public final java.lang.Integer getOrderNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.OrderNumber.toString());
	}

	/**
	 * Set value of OrderNumber
	 * @param ordernumber
	 */
	public final void setOrderNumber(java.lang.Integer ordernumber)
	{
		setOrderNumber(getContext(), ordernumber);
	}

	/**
	 * Set value of OrderNumber
	 * @param context
	 * @param ordernumber
	 */
	public final void setOrderNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer ordernumber)
	{
		getMendixObject().setValue(context, MemberNames.OrderNumber.toString(), ordernumber);
	}

	/**
	 * @return value of WarehouseID
	 */
	public final java.lang.Long getWarehouseID()
	{
		return getWarehouseID(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehouseID
	 */
	public final java.lang.Long getWarehouseID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.WarehouseID.toString());
	}

	/**
	 * Set value of WarehouseID
	 * @param warehouseid
	 */
	public final void setWarehouseID(java.lang.Long warehouseid)
	{
		setWarehouseID(getContext(), warehouseid);
	}

	/**
	 * Set value of WarehouseID
	 * @param context
	 * @param warehouseid
	 */
	public final void setWarehouseID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long warehouseid)
	{
		getMendixObject().setValue(context, MemberNames.WarehouseID.toString(), warehouseid);
	}

	/**
	 * @return value of SendDate
	 */
	public final java.util.Date getSendDate()
	{
		return getSendDate(getContext());
	}

	/**
	 * @param context
	 * @return value of SendDate
	 */
	public final java.util.Date getSendDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.SendDate.toString());
	}

	/**
	 * Set value of SendDate
	 * @param senddate
	 */
	public final void setSendDate(java.util.Date senddate)
	{
		setSendDate(getContext(), senddate);
	}

	/**
	 * Set value of SendDate
	 * @param context
	 * @param senddate
	 */
	public final void setSendDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date senddate)
	{
		getMendixObject().setValue(context, MemberNames.SendDate.toString(), senddate);
	}

	/**
	 * @return value of ShipmentNumber
	 */
	public final java.lang.Integer getShipmentNumber()
	{
		return getShipmentNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of ShipmentNumber
	 */
	public final java.lang.Integer getShipmentNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ShipmentNumber.toString());
	}

	/**
	 * Set value of ShipmentNumber
	 * @param shipmentnumber
	 */
	public final void setShipmentNumber(java.lang.Integer shipmentnumber)
	{
		setShipmentNumber(getContext(), shipmentnumber);
	}

	/**
	 * Set value of ShipmentNumber
	 * @param context
	 * @param shipmentnumber
	 */
	public final void setShipmentNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer shipmentnumber)
	{
		getMendixObject().setValue(context, MemberNames.ShipmentNumber.toString(), shipmentnumber);
	}

	/**
	 * @return value of ModeOfTransportation
	 */
	public final java.lang.String getModeOfTransportation()
	{
		return getModeOfTransportation(getContext());
	}

	/**
	 * @param context
	 * @return value of ModeOfTransportation
	 */
	public final java.lang.String getModeOfTransportation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ModeOfTransportation.toString());
	}

	/**
	 * Set value of ModeOfTransportation
	 * @param modeoftransportation
	 */
	public final void setModeOfTransportation(java.lang.String modeoftransportation)
	{
		setModeOfTransportation(getContext(), modeoftransportation);
	}

	/**
	 * Set value of ModeOfTransportation
	 * @param context
	 * @param modeoftransportation
	 */
	public final void setModeOfTransportation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String modeoftransportation)
	{
		getMendixObject().setValue(context, MemberNames.ModeOfTransportation.toString(), modeoftransportation);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Shipment_Order
	 */
	public final masterdata.proxies.Order getShipment_Order() throws com.mendix.core.CoreException
	{
		return getShipment_Order(getContext());
	}

	/**
	 * @param context
	 * @return value of Shipment_Order
	 * @throws com.mendix.core.CoreException
	 */
	public final masterdata.proxies.Order getShipment_Order(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		masterdata.proxies.Order result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Shipment_Order.toString());
		if (identifier != null) {
			result = masterdata.proxies.Order.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Shipment_Order
	 * @param shipment_order
	 */
	public final void setShipment_Order(masterdata.proxies.Order shipment_order)
	{
		setShipment_Order(getContext(), shipment_order);
	}

	/**
	 * Set value of Shipment_Order
	 * @param context
	 * @param shipment_order
	 */
	public final void setShipment_Order(com.mendix.systemwideinterfaces.core.IContext context, masterdata.proxies.Order shipment_order)
	{
		if (shipment_order == null) {
			getMendixObject().setValue(context, MemberNames.Shipment_Order.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Shipment_Order.toString(), shipment_order.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return shipmentMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final masterdata.proxies.Shipment that = (masterdata.proxies.Shipment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
